"""initial_migration

Revision ID: 2b44dcf5744f
Revises: 
Create Date: 2025-04-18 13:51:02.849657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b44dcf5744f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('access_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('access_id > 0', name='access_id_positive_number_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_index('uix_category_name_lower', 'category', [sa.literal_column("lower('category_name')")], unique=True)
    op.create_table('dimensionunit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension_name', sa.String(length=255), nullable=False),
    sa.Column('dimension_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('access_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('access_id > 0', name='access_id_positive_number_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension_name')
    )
    op.create_index('uix_dimension_code_lower', 'dimensionunit', [sa.literal_column("lower('dimension_code')")], unique=True)
    op.create_index('uix_dimension_name_lower', 'dimensionunit', [sa.literal_column("lower('dimension_name')")], unique=True)
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_name', sa.String(length=255), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('ggg', sa.Boolean(), server_default='True', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('access_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('access_id > 0', name='access_id_positive_number_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uix_manufacturer_name_lower', 'manufacturer', [sa.literal_column('lower(manufacturer_name)')], unique=True)
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcategory_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('control', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('access_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('access_id > 0', name='access_id_positive_number_check'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subcategory_name')
    )
    op.create_index('uix_subcategory_name_lower', 'subcategory', [sa.literal_column("lower('subcategory_name')")], unique=True)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('artikul', sa.String(length=255), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('dimension_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.String(length=255), nullable=True),
    sa.Column('date_create', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_moderated', sa.Boolean(), nullable=False),
    sa.Column('date_moderated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name_full', sa.String(length=2000), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('access_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('access_id > 0', name='access_id_positive_number_check'),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensionunit.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('artikul_idx', 'product', [sa.literal_column("lower('artikul')")], unique=False)
    op.create_index('name_full_idx', 'product', [sa.literal_column("lower('name_full')")], unique=False)
    op.create_index('product_name_idx', 'product', [sa.literal_column("lower('product_name')")], unique=False)
    op.create_index('uix_product_unique', 'product', [sa.literal_column("lower('product_name')"), 'manufacturer_id', sa.literal_column("lower('artikul')"), 'dimension_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_product_unique', table_name='product')
    op.drop_index('product_name_idx', table_name='product')
    op.drop_index('name_full_idx', table_name='product')
    op.drop_index('artikul_idx', table_name='product')
    op.drop_table('product')
    op.drop_index('uix_subcategory_name_lower', table_name='subcategory')
    op.drop_table('subcategory')
    op.drop_index('uix_manufacturer_name_lower', table_name='manufacturer')
    op.drop_table('manufacturer')
    op.drop_index('uix_dimension_name_lower', table_name='dimensionunit')
    op.drop_index('uix_dimension_code_lower', table_name='dimensionunit')
    op.drop_table('dimensionunit')
    op.drop_index('uix_category_name_lower', table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
