"""Auto-generated migration

Revision ID: 7129635073b9
Revises: 2b44dcf5744f
Create Date: 2025-04-18 13:52:22.055149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7129635073b9'
down_revision: Union[str, None] = '2b44dcf5744f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manufacturer', 'ggg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturer', sa.Column('ggg', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
