"""Auto-generated migration

Revision ID: ef11ac20cb9b
Revises: bbe3e076c275
Create Date: 2025-04-22 16:10:33.758498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef11ac20cb9b'
down_revision: Union[str, None] = 'bbe3e076c275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=False),
    sa.Column('profession', sa.Enum('DEVELOPER', 'DESIGNER', 'MANAGER', name='professionenum'), server_default=sa.text("'MANAGER'"), nullable=False),
    sa.Column('profession2', sa.String(length=50), server_default=sa.text("'MANAGER'"), nullable=False),
    sa.Column('profession3', sa.Enum('DEVELOPER', 'DESIGNER', 'MANAGER', name='professionenum', native_enum=False, length=255), server_default=sa.text("'MANAGER'"), nullable=False),
    sa.Column('interests', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('contacts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('access_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
